# Generated by Django 5.0.3 on 2024-03-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='employee',
            new_name='user',
        ),
    ]
