# Generated by Django 5.0.3 on 2024-05-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_alter_auditlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='input_data',
            field=models.TextField(default='request data'),
            preserve_default=False,
        ),
    ]
