# Generated by Django 5.0.3 on 2024-05-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_auditlog_input_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='status_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
