# Generated by Django 5.0.3 on 2024-05-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0005_alter_auditlog_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='input_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='status_code',
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
    ]
