# Generated by Django 5.0.3 on 2024-05-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0007_userslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslog',
            name='changes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
