# Generated by Django 5.0.3 on 2024-05-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0008_userslog_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslog',
            name='object_repr',
            field=models.TextField(blank=True),
        ),
    ]
