# Generated by Django 5.0.3 on 2024-05-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name_plural': 'Transactions'},
        ),
    ]
